numpy基础学习

In [18]:
import numpy as np
a = [0,2.,4,6,8,10,12]
a = np.array(a)
a[0:4:2]
a[3]
a[4]
a[[3,4]]
"""
array([6., 8.])
"""

b = np.arange(12).reshape(3,4)
b[1], b[1,1]
""" 
array([4, 5, 6, 7]), 5
"""
b[[1,2],[1,2]] ,b[1,1],b[2,2]
""" 
一个非常有意思的索引机制
array([ 5, 10]), 5, 10
"""

(array([ 5, 10]), 5, 10)

In [49]:
a = np.arange(12).reshape(3,4)
a
""" 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
"""
a > 5
""" 
array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])
"""
a - 2
"""
array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])
"""
a[a>5]
""" 
array([ 6,  7,  8,  9, 10, 11])
"""
# 获取所有的奇数
a[a%2==1]
""" 
array([ 1,  3,  5,  7,  9, 11])
"""
# 将奇数都赋值为0
a[a%2==1]=0 
a
""" 
array([[ 0,  0,  2,  0],
       [ 4,  0,  6,  0],
       [ 8,  0, 10,  0]])
"""
# relu函数
a=  np.arange(-6,6).reshape(3,4)
a[a<0]=0
a


array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [2, 3, 4, 5]])

In [62]:

# 关于广播机制
a=np.arange(12).reshape(3,4)
b = np.array([1,2,3,4])
a,b,a-b
""" 
(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([1, 2, 3, 4]),
 array([[-1, -1, -1, -1],
        [ 3,  3,  3,  3],
        [ 7,  7,  7,  7]]))
"""
b = np.array([[1,2,3,4],[5,6,7,8]])
# a,b,a-b
""" 
ValueError: operands could not be broadcast together with shapes (3,4) (2,4)
"""

b=np.array([1,2,3])
# a,b,a-b
""" 
operands could not be broadcast together with shapes (3,4) (3,)
"""
b=np.array([1,2,3]).reshape(3,1)
a,b,a-b
""" 
(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[1],
        [2],
        [3]]),
 array([[-1,  0,  1,  2],
        [ 2,  3,  4,  5],
        [ 5,  6,  7,  8]]))
"""

""" 
广播的两种条件
(3,4) 和 (4,)
(3,4) 和 (3,1)

1. 后缀维度相符，可以做广播
比如 (3,4,5) 就可以和 (5,) (4,5)
2. 其中有一个轴的维度为1，其余都相同
"""
a = np.arange(3*4*5).reshape(3,4,5)
b = np.random.rand(1*5).reshape(-1,5)
c = np.ones((4,5)).reshape(-1,4,5)
a-b,a-c
# 成功

a=np.zeros((4,4,4))
b=np.ones((4,4,1))
a-b
# 成功

a=np.zeros((4,4,4))
b=np.ones((4,4,2))
# a-b
# error

In [68]:
a = np.arange(12).reshape(3,4)

a.transpose(0,1)# a保持不变
""" 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
"""

a.T, a.transpose(1,0)
""" 
array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
"""

' \narray([[ 0,  4,  8],\n        [ 1,  5,  9],\n        [ 2,  6, 10],\n        [ 3,  7, 11]]),\n array([[ 0,  4,  8],\n        [ 1,  5,  9],\n        [ 2,  6, 10],\n        [ 3,  7, 11]])\n'

Object `inf` not found.
